import Link from 'next/link';
import Header from '../../components/Header';
import Footer from '../../components/Footer';

const offers = [
  { category:'Elektronarzędzia', name:'Wiertarko-wkrętarka akumulatorowa 21V', retail:'162–223 zł', wholesale:'wycena wolumenowa', use:'Montaż, serwis, utrzymanie ruchu i mobilne stanowiska techniczne.', functions:'Wiercenie i wkręcanie w pracach montażowych; mobilna praca na platformie akumulatorowej.', specs:'Platforma akumulatorowa 21V; dokładna konfiguracja, moment, akumulatory i osprzęt potwierdzane przed ofertą.' },
  { category:'Narzędzia spalinowe', name:'Profesjonalne narzędzie spalinowe — konfiguracja branżowa', retail:'wycena indywidualna', wholesale:'wycena wolumenowa', use:'Prace terenowe, komunalne, budowlane i utrzymanie infrastruktury.', functions:'Dobór jednostki roboczej i osprzętu do profilu przedsiębiorstwa oraz środowiska pracy.', specs:'Typ silnika, moc, masa, emisje, wyposażenie ochronne i zgodność dla rynku UE wymagają potwierdzenia dla konkretnego modelu.' },
  { category:'Narzędzia manualne', name:'Modułowy zestaw narzędzi ręcznych klasy profesjonalnej', retail:'wycena indywidualna', wholesale:'wycena wolumenowa', use:'Serwis, montaż, warsztat, instalacje i mobilne ekipy techniczne.', functions:'Modułowa konfiguracja zestawu według specjalności stanowiska i zakresu wykonywanych prac.', specs:'Skład zestawu, materiały, normy narzędzi i wyposażenie stanowiska dobierane do branży klienta.' },
  { category:'Stanowisko / warsztat', name:'Modułowe stanowisko serwisowo-warsztatowe', retail:'wycena indywidualna', wholesale:'wycena projektowa', use:'Produkcja, serwis, laboratoria techniczne, utrzymanie ruchu i zaplecza warsztatowe.', functions:'Organizacja miejsca pracy, przechowywania narzędzi, zasilania i opcjonalnej ochrony ESD.', specs:'Blat, szafki, organizacja narzędzi, ESD i zasilanie dobierane do zastosowania; parametry potwierdzane w projekcie.' },
  { category:'Maszyny profesjonalne', name:'Minikoparka klasy ok. 2 t — konfiguracja bazowa', retail:'ok. 21 782 zł — wartość referencyjna', wholesale:'wycena wolumenowa', use:'Roboty ziemne, instalacyjne, komunalne i prace na ograniczonej przestrzeni.', functions:'Prace ziemne z osprzętem dobieranym do zadania i warunków placu budowy.', specs:'Klasa masy ok. 2 t; silnik, masa robocza, osprzęt, dokumentacja CE i konfiguracja muszą zostać ponownie sprawdzone przed ofertą wiążącą.' },
  { category:'Energia / HVAC / infrastruktura', name:'System infrastruktury przedsiębiorstwa — konfiguracja projektowa', retail:'wycena indywidualna', wholesale:'wycena projektowa', use:'Energia, magazynowanie, HVAC, zasilanie awaryjne i infrastruktura techniczna obiektu.', functions:'Projektowe zestawienie urządzeń i parametrów dla zapotrzebowania energetycznego lub środowiskowego obiektu.', specs:'Moc, pojemność, napięcia, sprawność, warunki środowiskowe i wymagane dokumenty zależą od projektu.' },
];

export default function EnterpriseEquipmentPage(){
  return <><Header/><main style={{background:'#f6f8f9',color:'#172126',minHeight:'100vh'}}>
    <section style={{background:'#122027',color:'#fff',padding:'56px 24px'}}><div style={{maxWidth:1120,margin:'0 auto'}}><p style={{color:'#f0d778',fontWeight:700,letterSpacing:'.12em'}}>WYPOSAŻENIE PRZEDSIĘBIORSTW • TOWAR PRZEWOZOWY</p><h1>Profesjonalne wyposażenie dla przedsiębiorstw wielu branż</h1><p style={{maxWidth:880,lineHeight:1.7,color:'#d5dde0'}}>Przekrojowa oferta narzędzi, stanowisk, maszyn i infrastruktury technicznej. Konkretna marka, model, parametry, dokumentacja zgodności, zdjęcia i materiały prezentacyjne są publikowane jako zweryfikowane dopiero po potwierdzeniu dla danej konfiguracji i uzyskaniu prawa do wykorzystania materiału.</p><Link href='/offers/new?product=Wyposażenie%20przedsiębiorstwa' style={{color:'#f0d778',fontWeight:700}}>ZAPYTAJ O INDYWIDUALNĄ KONFIGURACJĘ →</Link></div></section>
    <section style={{maxWidth:1120,margin:'0 auto',padding:'42px 24px'}}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:18}}>{offers.map((o,i)=><article key={o.category} style={{background:'#fff',border:'1px solid #dde3e6',borderRadius:16,padding:22}}><small style={{color:'#687980'}}>OFERTA {String(i+1).padStart(2,'0')} • {o.category}</small><h2 style={{fontSize:21}}>{o.name}</h2><p><strong>Funkcje:</strong> {o.functions}</p><p><strong>Zastosowanie:</strong> {o.use}</p><p><strong>Parametry techniczne:</strong> {o.specs}</p><p><strong>Cena detaliczna orientacyjna:</strong> {o.retail}</p><p><strong>Cena hurtowa orientacyjna:</strong> {o.wholesale}</p><p><strong>Dostawa:</strong> termin potwierdzany w ofercie; dla sprzedaży detalicznej może zostać uzgodniony termin do 75 dni.</p><p style={{color:'#607178',fontSize:13}}>Marka/model, dostępność, kompletna specyfikacja, cena i dokumentacja zgodności są potwierdzane przed ofertą wiążącą. Brak potwierdzonego dowodu oznacza brak statusu „zweryfikowane”.</p><Link href={`/offers/new?product=${encodeURIComponent(o.name)}`}>POPROŚ O WYCENĘ →</Link></article>)}</div></section>
    <section style={{maxWidth:1120,margin:'0 auto',padding:'0 24px 56px'}}><div style={{background:'#fff',border:'1px solid #dde3e6',borderRadius:18,padding:28}}><p style={{color:'#607178',fontWeight:700}}>WARUNKI OPERACYJNE TOWARU PRZEWOZOWEGO</p><h2>Założenia realizacji — potwierdzane w zaakceptowanej ofercie</h2><p style={{lineHeight:1.7}}>Dla sprzedaży detalicznej można uzgodnić maksymalny termin dostawy do 75 dni, liczony od zdarzenia wskazanego w zaakceptowanej ofercie lub umowie. Płatność do 25. dnia roboczego danego cyklu obowiązuje wyłącznie wtedy, gdy została jednoznacznie przyjęta w umowie.</p><p style={{lineHeight:1.7}}>Sformułowanie „45. dzień miesiąca” nie jest stosowane, ponieważ miesiąc kalendarzowy nie ma 45 dni. Jeżeli strony stosują cykl dłuższy niż miesiąc, termin może zostać określony jako „45. dzień cyklu rozliczeniowego” wraz z jednoznaczną datą początkową.</p><p style={{lineHeight:1.7}}><strong>Finansowanie inwestycyjne / monetyzacja należności:</strong> dostępność i warunki są ustalane indywidualnie po wymaganej analizie prawnej i transakcyjnej, KYC/KYB/AML oraz potwierdzeniu finansującego. Materiał nie stanowi gwarancji przyznania finansowania, określonej kwoty, oprocentowania ani emisji pieniądza elektronicznego.</p></div></section>
  </main><Footer/></>;
}
