'use client';
import { useMemo, useState } from 'react';
import catalogTaxonomy, { type TaxonomyBranch } from '../data/catalogTaxonomy';
import { defaultSafetyNotice, durabilityNotice, premiumQualificationNotice, variantsForCategory } from '../data/catalogOfferProfiles';

type LeafPath={category:string;path:string[];leaf:string};
const variants=['SELECT','PREMIUM','PLUS','PRO','PRO MAX','BUSINESS','CREATOR','PERFORMANCE','SIGNATURE','LUXURY'];
function collectLeaves(b:TaxonomyBranch,p:string[]=[]):string[][]{const n=[...p,b.name];return b.children?.length?b.children.flatMap(c=>collectLeaves(c,n)):[n]}
function leaves():LeafPath[]{return catalogTaxonomy.flatMap(c=>collectLeaves(c).map(path=>({category:c.name,path,leaf:path.at(-1)!})))}
function Tree({branches,depth=0}:{branches:TaxonomyBranch[];depth?:number}){return <div className={`taxonomy-tree taxonomy-depth-${depth}`}>{branches.map(b=><details key={`${depth}-${b.name}`} open={depth===0}><summary>{b.name}<span>{b.children?.length?`${b.children.length} elementów`:'10 kandydatów'}</span></summary>{b.children?.length?<Tree branches={b.children} depth={depth+1}/>:null}</details>)}</div>}
function functionText(leaf:string){return `Realizuje podstawową funkcję właściwą dla kategorii „${leaf}”, w konfiguracji dobranej do parametrów technicznych, jakościowych i użytkowych zamawiającego.`}
function useText(leaf:string){return `Do profesjonalnego lub konsumenckiego zastosowania zgodnego z przeznaczeniem kategorii „${leaf}”; przed sprzedażą określane są środowisko pracy, obciążenie, kompatybilność i wymagany rezultat.`}
function purposeText(leaf:string){return `Wyposażenie, modernizacja, inwestycja, integracja, produkcja, eksploatacja lub dalsza odsprzedaż — zależnie od konkretnego produktu z grupy „${leaf}”.`}
function visual(label:string){const s=`<svg xmlns='http://www.w3.org/2000/svg' width='900' height='520'><rect width='100%' height='100%' fill='#0b171b'/><text x='50%' y='46%' text-anchor='middle' fill='#d4af37' font-size='72' font-family='Arial'>PREMIUM</text><text x='50%' y='59%' text-anchor='middle' fill='#d7e3e5' font-size='28' font-family='Arial'>${label.replace(/&/g,'&amp;')}</text></svg>`;return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(s)}`}
export default function HierarchicalCatalog(){const all=useMemo(()=>leaves(),[]);const [q,setQ]=useState('');const [cat,setCat]=useState('Wszystkie');const filtered=useMemo(()=>all.filter(x=>(cat==='Wszystkie'||x.category===cat)&&(!q.trim()||x.path.join(' ').toLowerCase().includes(q.toLowerCase()))),[all,q,cat]);const total=all.reduce((s,x)=>s+variantsForCategory(x.category,x.path.join('/')),0);return <>
<section className='section catalog-taxonomy-summary'><div className='catalog-meta'><div><strong>{catalogTaxonomy.length}</strong><span>głównych działów</span></div><div><strong>{all.length}</strong><span>elementów końcowych</span></div><div><strong>{total}</strong><span>kandydatów ofertowych — dokładnie 10 na element</span></div></div><p className='catalog-count'>Rozbudowany katalog zastępuje wcześniejszy ograniczony katalog B2B. Każdy element ma 10 kandydatów sourcingowych PREMIUM. Kandydat staje się zweryfikowaną ofertą dopiero po wskazaniu konkretnego producenta/modelu oraz potwierdzeniu jakości, trwałości, dostępności, gwarancji i wymaganych dokumentów zgodności.</p></section>
<section className='section taxonomy-browser'><div className='catalog-toolbar'><input value={q} onChange={e=>setQ(e.target.value)} placeholder='Szukaj kategorii, zastosowania lub produktu…'/><select value={cat} onChange={e=>setCat(e.target.value)}><option>Wszystkie</option>{catalogTaxonomy.map(x=><option key={x.name}>{x.name}</option>)}</select></div><p className='catalog-count'>Widok: <strong>{filtered.length}</strong> elementów / <strong>{filtered.length*10}</strong> kandydatów ofertowych.</p><div className='taxonomy-layout'><aside className='taxonomy-sidebar'><h3>Rozbudowane drzewo kategorii</h3><Tree branches={catalogTaxonomy}/></aside><div className='taxonomy-products'>{filtered.map((item,li)=><section className='taxonomy-leaf' key={item.path.join('/')}><div className='taxonomy-leaf-heading'><div><p className='eyebrow'>{item.category}</p><h2>{item.leaf}</h2><p>{item.path.join(' / ')}</p></div><span>10 kandydatów PREMIUM</span></div><div className='taxonomy-product-grid'>{variants.map((v,i)=>{const name=`${item.leaf} ${v}`;return <article className='taxonomy-product-card' key={v}><div className='taxonomy-product-number'>{String(li+1).padStart(3,'0')}.{String(i+1).padStart(2,'0')}</div><img className='taxonomy-product-image' src={visual(name)} alt={`${name} — prezentacja`} loading='lazy'/><p className='eyebrow'>KANDYDAT PREMIUM • TRWAŁOŚĆ I ZGODNOŚĆ DO WERYFIKACJI</p><h3>{name}</h3><p><strong>Do czego można użyć:</strong> {useText(item.leaf)}</p><p><strong>Przeznaczenie:</strong> {purposeText(item.leaf)}</p><p><strong>Jaką funkcję spełnia:</strong> {functionText(item.leaf)}</p><p><strong>Jakość i trwałość:</strong> {durabilityNotice}</p><p><strong>Certyfikacja i zgodność:</strong> {premiumQualificationNotice}</p><p><strong>Bezpieczne użytkowanie:</strong> {defaultSafetyNotice}</p><p><strong>Dokumentacja:</strong> karta techniczna, instrukcja, warunki gwarancji oraz wymagane dla danego produktu deklaracje/certyfikaty są sprawdzane przed zatwierdzeniem konkretnego modelu. Nie oznaczamy produktu jako certyfikowany bez dokumentu źródłowego.</p><a className='taxonomy-offer-link' href={`/offers/new?product=${encodeURIComponent(name)}&category=${encodeURIComponent(item.path.join(' / '))}`}>Poproś o dobór konkretnego produktu i weryfikację dokumentacji →</a></article>})}</div></section>)}</div></div></section></>}
